version: '3.8'

services:
  # 1. PostgreSQL: Ana Veritabanımız (Wallet ve Order için)
  postgres:
    image: postgres:16-alpine
    container_name: fintech-postgres
    environment:
      - POSTGRES_USER=fintechuser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=fintech_wallet # Varsayılan olarak bu DB ile açılacak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # Veriler kaybolmasın diye volume

  # 2. Redis: Cache ve Ticker (Canlı borsa verisi) için
  redis:
    image: redis:7.0-alpine
    container_name: fintech-redis
    ports:
      - "6379:6379"

  # 3. Zookeeper: Kafka'nın çalışması için gerekli koordinatör
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: fintech-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # 4. Kafka: Mesajlaşma Kuyruğu (Event Streaming)
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: fintech-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  postgres_data: