server:
  port: 8082 # DİKKAT: Port 8082

spring:
  application:
    name: order-service

  # Database Ayarları (fintech_order veritabanı)
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech_order
    username: fintechuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Redis Ayarı (EKLENECEK)
  data:
    redis:
      host: localhost
      port: 6379

  # Kafka Ayarları (Şimdilik basit bağlantı)
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: order-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*" # Tüm paketlere güven (Event nesnesini tanıması için)
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  grpc:
    client:
      wallet-service:
        address: static://localhost:9090
        negotiation-type: plaintext